core/routes/auth.py
from flask import Blueprint, redirect, url_for, request, flash, render_template
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from ..models import User
from ..extensions import db
from ..functions import validate_password, validate_email, validate_username

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/')
def index():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    else:
        return redirect(url_for('main.index'))
    
'''
Login routes
'''

@auth.route('/login/', methods=['GET'])
def login_get():
    if not current_user.is_authenticated:
        context = {
            'title': 'Login | My Fitness Cat',
        }
        return render_template(
            'auth/login.html',
            **context
        )
    else:
        return redirect(url_for('main.index'))

@auth.route('/login/', methods=['POST'])
def login():
    if not current_user.is_authenticated:
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()

        if user is None or not check_password_hash(user.password_hash, password):
            flash('Invalid username or password', 'error')
            return redirect(url_for('auth.login'))
        else:
            login_user(user, remember=True)
            flash('Logged in', 'success')
            return redirect(url_for('main.get_cats'))
    else: 
        flash('Already Logged in')
        return redirect(url_for('main.get_cats'))

'''
register routes
'''

@auth.route('/register/', methods=['GET'])
def register_get():
    if not current_user.is_authenticated:
        context = {
            'title': 'Register | My Fitness Cat'
        }

        return render_template(
            'auth/register.html',
            **context
        )
    else:
        return redirect(url_for('main.index'))
    
@auth.route('/register/', methods=['POST'])
def register():
    if not current_user.is_authenticated:
        username = request.form.get('username')
        password = request.form.get('password')
        password_check = request.form.get('password_check')
        email = request.form.get('email')
        first_name = request.form.get('f_name')

        # validation
        if not validate_password(password):
            flash('Invalid password.')
            return redirect(url_for('auth.register'))
        elif not password == password_check:
            flash('Passwords do not')
            return redirect(url_for('auth.register'))
        elif not validate_email(email):
            flash('Invalid email.')
            return redirect(url_for('auth.register'))
        elif not validate_username(username):
            flash('Invalid username.')
            return redirect(url_for('auth.register'))
        else: 
            password_hash = generate_password_hash(password, method='sha256')

        # create new user
        user = User(
            username=username,
            password_hash=password_hash,
            email=email,
            first_name=first_name,
        )

        db.session.add(user)
        db.session.commit()

        return 'User added'
    else:
        return 'Already Logged in'

'''
Logout routes
'''
    
@auth.route('/logout/')
def logout():
    if not current_user.is_authenticated:
        flash("You are not logged in", "error")
        return redirect(url_for('auth.login'))
    else:
        logout_user()
        flash("Logged Out Successfully", "success")
        return redirect(url_for('auth.login'))

core/routes/main.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, jsonify
from flask_login import current_user, login_required

from datetime import date

from ..models import Cat, owner_cat, Food, cat_food
from ..extensions import db
from ..functions import get_user_cats

main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
def index():
    name = request.args.get('name')
    weight = request.args.get('weight')
    age = request.args.get('age')

    if weight and name and age:
        calories = round(int(weight) ** 0.75 * 70 * 1.6)
    else:
        calories = 0

    context = {
        'title': 'Home | My Fitness Cat',
        'name': name,
        'weight': weight,
        'age': age,
        'calories': calories
    }

    return render_template(
        'main/index.html',
        **context
    )

'''
Add cat routes
'''

@main.route('/add-cat/', methods=['GET'])
@login_required
def add_cat_get():
    context = {
        'title': 'Add Cat | My Fitness Cat'
    }
    return render_template(
        'main/add.html',
        **context
    )

@main.route('/add-cat/', methods=['POST'])
@login_required
def add_cat():
    user = current_user
    weight = request.form.get('weight')
    weight_class = request.form.get('weight_class')
    is_neutered_input = request.form.get('is_neutered')
    name = request.form.get('name')
    dob_day = request.form.get('dob_day')
    dob_month = request.form.get('dob_month')
    dob_year = request.form.get('dob_year')

    dob = date(
        day=int(dob_day), 
        month=int(dob_month), 
        year=int(dob_year)
    )

    if is_neutered_input == 'false':
        is_neutered = False
    elif is_neutered_input == 'true':
        is_neutered = True
    else:
        return 'Please enter a valid input'

    new_cat = Cat(
        weight=float(weight),
        weight_class=weight_class,
        is_neutered=is_neutered,
        name=name,
        dob=dob
    )

    db.session.add(new_cat)
    db.session.commit()

    user_cat = owner_cat.insert().values(
        owner_id=user.id,
        cat_id=new_cat.id
    )

    db.session.execute(user_cat)
    db.session.commit()

    return redirect(url_for('main.get_cats'))

'''
View cats routes
'''

@main.route('/my-cats/', methods=['GET'])
@login_required
def get_cats():
    cats = [cat for cat in current_user.cats]
    print(cats)

    context = {
        'title': 'My Cats | My Fitness Cat',
        'cats': cats,
        'user': current_user
    }
    return render_template(
        'main/view_all.html',
        **context
    )

@main.route('/my-cats/json/', methods=['GET'])
@login_required
def get_cats_json():
    cats = [cat.to_dict() for cat in get_user_cats()]

    return jsonify(cats)

    
@main.route('/my-cats/<int:cat_id>/', methods=['GET'])
@login_required
def get_cat(cat_id):
    found_cat = [cat.to_dict() for cat in get_user_cats() if cat.id == cat_id]

    context = {
        'title': 'My Cats | My Fitness Cat',
        'found_cat': found_cat[0]
    }
    return render_template(
        'main/view_one.html',
        **context
    )

@main.route('/my-cats/<int:cat_id>/json/', methods=['GET'])
@login_required
def get_cat_json(cat_id):
    found_cat = [cat.to_dict() for cat in get_user_cats() if cat.id == cat_id]

    return jsonify(found_cat)

# @main.route('/my-cats/<int:cat_id>/delete/', methods=['DELETE'])
# @login_required
# def delete_cat_get(cat_id):


@main.route('/my-cats/<int:cat_id>/delete/', methods=['GET'])
@login_required
def delete_cat(cat_id):
    cats = [cat for cat in get_user_cats() if cat.id == cat_id]
    found_cat = cats[0]
    if found_cat:
        db.session.delete(found_cat)
        db.session.commit()
        flash(f'Cat {found_cat.name} deleted')
        return redirect(url_for('main.get_cats'))
    
    raise ValueError('Cat not found')

'''
edit cat routes
'''

@main.route('/my-cats/<int:cat_id>/edit/', methods=['GET'])
@login_required
def edit_cat_get(cat_id):
    cats = [cat for cat in get_user_cats() if cat.id == cat_id]
    found_cat = cats[0]

    context = {
        'title': 'Edit Cat | My Fitness Cat',
        'found_cat': found_cat
    }

    return render_template(
        'main/edit-cat.html',
        **context
    )

@main.route('/my-cats/<int:cat_id>/edit/', methods=['POST'])
@login_required
def edit_cat(cat_id):
    found_cat = [cat for cat in get_user_cats() if cat.id == cat_id][0]

    weight = request.form.get('weight')
    weight_class = request.form.get('weight_class')
    is_neutered_input = request.form.get('is_neutered')
    dob_day = request.form.get('dob_day')
    dob_month = request.form.get('dob_month')
    dob_year = request.form.get('dob_year')

    breed = request.form.get('breed')
    color = request.form.get('color')

    if found_cat:
        if weight:
            found_cat.weight = float(weight)
        if weight_class:
            found_cat.weight_class = str(weight_class)
        if is_neutered_input:
            found_cat.is_neutered = True if is_neutered_input == 'true' else False
        if dob_day and dob_month and dob_year:
            found_cat.dob = date(day=int(dob_day), month=int(dob_month), year=int(dob_year))
        if breed:
            found_cat.breed = str(breed).strip()
        if color:
            found_cat.color = str(color).strip()

        db.session.commit()
        return redirect(url_for('main.get_cats'))
    
    raise ValueError('Cat not found')

@main.route('/my-cats/<int:cat_id>/add-food/<int:food_id>/')
@login_required
def add_cat_food(cat_id, food_id):
    cat = Cat.query.get(cat_id)
    food = Food.query.get(food_id)

    if cat is None or food is None:
        return 'Invalid cat or food ID'

    existing_food = db.session.query(cat_food).filter(cat_food.c.cat_id == cat_id).first()

    if existing_food:
        delete_query = cat_food.delete().where(cat_food.c.cat_id == cat_id)
        db.session.execute(delete_query)
        db.session.commit()

    insert_query = cat_food.insert().values(cat_id=cat_id, food_id=food_id)
    db.session.execute(insert_query)
    db.session.commit()

    return 'Cat food added successfully'

core/templates/includes/base.html
<!DOCTYPE html>
<html lang="en">
    <!-- base.html -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {{ title }}
    </title>
    {% if request.args.get('theme') == 'dark' %}
        <link rel="stylesheet" href="{{url_for('static', filename='css/root_dark.css')}}">
    {% else %}
        <link rel="stylesheet" href="{{url_for('static', filename='css/root.css')}}">
    {% endif %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="shortcut icon" href="{{url_for('static', filename='icon/favicon.ico')}}">
</head>
<body>
    <div class="full-wrapper">
        {% include 'includes/header.html' %}
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="flashes">
                {% for category, message in messages %}
                <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
        <div class="container">
            
            {% block content %}
            {% endblock %}
        </div>
        {% include 'includes/footer.html' %}
    </div>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

core/templates/includes/footer.html
<footer>
    <p>Copyright &copy; 2023 Josh Shepherd</p>
</footer>

core/templates/includes/header.html
<header>
    <h2><a href="{{url_for('main.index')}}">My Fitness Cat<span>
        <i class="fa-sharp fa-solid fa-cat"></i></a>
    </span></h2>
    <nav>
        <ul class="nav">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.get_cats')}}">Your Cats</a></li>
            <li><a href="{{url_for('main.add_cat')}}">Add Cat</a></li>
            <li><a href="{{url_for('auth.logout')}}">
                <span>Logout</span>
                <span>
                    <i class="fa-solid fa-right-from-bracket"></i>
                </span>
            </a></li>
            {% endif %}
            {% if not current_user.is_authenticated %}
            <li><a href="{{url_for('auth.login')}}">
                <span>Login</span>
                <span>
                    <i class="fa-solid fa-right-to-bracket"></i>
                </span>
            </a></li>
            <li><a href="{{url_for('auth.register')}}">
                <span>Register</span>
                <span>
                    <i class="fa-solid fa-user-plus"></i>
                </span>
            </a></li>
            {% endif %}
        </ul>
    </nav>
</header>