core/routes/main.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, jsonify
from flask_login import current_user, login_required

from datetime import date

from ..models import Cat, owner_cat, Food, cat_food
from ..extensions import db
from ..functions import get_user_cats

main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
def index():
    name = request.args.get('name')
    weight = request.args.get('weight')
    age = request.args.get('age')

    if weight and name and age:
        calories = round(int(weight) ** 0.75 * 70 * 1.6)
    else:
        calories = 0

    context = {
        'title': 'Home | My Fitness Cat',
        'name': name,
        'weight': weight,
        'age': age,
        'calories': calories
    }

    return render_template(
        'main/index.html',
        **context
    )

'''
Add cat routes
'''

@main.route('/add-cat/', methods=['GET'])
@login_required
def add_cat_get():
    context = {
        'title': 'Add Cat | My Fitness Cat'
    }
    return render_template(
        'main/add.html',
        **context
    )

@main.route('/add-cat/', methods=['POST'])
@login_required
def add_cat():
    user = current_user
    weight = request.form.get('weight')
    weight_class = request.form.get('weight_class')
    is_neutered_input = request.form.get('is_neutered')
    name = request.form.get('name')
    dob_day = request.form.get('dob_day')
    dob_month = request.form.get('dob_month')
    dob_year = request.form.get('dob_year')

    dob = date(
        day=int(dob_day), 
        month=int(dob_month), 
        year=int(dob_year)
    )

    if is_neutered_input == 'false':
        is_neutered = False
    elif is_neutered_input == 'true':
        is_neutered = True
    else:
        return 'Please enter a valid input'

    new_cat = Cat(
        weight=float(weight),
        weight_class=weight_class,
        is_neutered=is_neutered,
        name=name,
        dob=dob
    )

    db.session.add(new_cat)
    db.session.commit()

    user_cat = owner_cat.insert().values(
        owner_id=user.id,
        cat_id=new_cat.id
    )

    db.session.execute(user_cat)
    db.session.commit()

    return redirect(url_for('main.get_cats'))

'''
View cats routes
'''

@main.route('/my-cats/', methods=['GET'])
@login_required
def get_cats():
    cats = [cat for cat in current_user.cats]
    print(cats)

    context = {
        'title': 'My Cats | My Fitness Cat',
        'cats': cats,
        'user': current_user
    }
    return render_template(
        'main/view_all.html',
        **context
    )

@main.route('/my-cats/json/', methods=['GET'])
@login_required
def get_cats_json():
    cats = [cat.to_dict() for cat in get_user_cats()]

    return jsonify(cats)

    
@main.route('/my-cats/<int:cat_id>/', methods=['GET'])
@login_required
def get_cat(cat_id):
    found_cat = [cat.to_dict() for cat in get_user_cats() if cat.id == cat_id]

    context = {
        'title': 'My Cats | My Fitness Cat',
        'found_cat': found_cat[0]
    }
    return render_template(
        'main/view_one.html',
        **context
    )

@main.route('/my-cats/<int:cat_id>/json/', methods=['GET'])
@login_required
def get_cat_json(cat_id):
    found_cat = [cat.to_dict() for cat in get_user_cats() if cat.id == cat_id]

    return jsonify(found_cat)

# @main.route('/my-cats/<int:cat_id>/delete/', methods=['DELETE'])
# @login_required
# def delete_cat_get(cat_id):


@main.route('/my-cats/<int:cat_id>/delete/', methods=['GET'])
@login_required
def delete_cat(cat_id):
    cats = [cat for cat in get_user_cats() if cat.id == cat_id]
    found_cat = cats[0]
    if found_cat:
        db.session.delete(found_cat)
        db.session.commit()
        flash(f'Cat {found_cat.name} deleted')
        return redirect(url_for('main.get_cats'))
    
    raise ValueError('Cat not found')

'''
edit cat routes
'''

@main.route('/my-cats/<int:cat_id>/edit/', methods=['GET'])
@login_required
def edit_cat_get(cat_id):
    cats = [cat for cat in get_user_cats() if cat.id == cat_id]
    found_cat = cats[0]

    context = {
        'title': 'Edit Cat | My Fitness Cat',
        'found_cat': found_cat
    }

    return render_template(
        'main/edit-cat.html',
        **context
    )

@main.route('/my-cats/<int:cat_id>/edit/', methods=['POST'])
@login_required
def edit_cat(cat_id):
    found_cat = [cat for cat in get_user_cats() if cat.id == cat_id][0]

    weight = request.form.get('weight')
    weight_class = request.form.get('weight_class')
    is_neutered_input = request.form.get('is_neutered')
    dob_day = request.form.get('dob_day')
    dob_month = request.form.get('dob_month')
    dob_year = request.form.get('dob_year')

    breed = request.form.get('breed')
    color = request.form.get('color')

    if found_cat:
        if weight:
            found_cat.weight = float(weight)
        if weight_class:
            found_cat.weight_class = str(weight_class)
        if is_neutered_input:
            found_cat.is_neutered = True if is_neutered_input == 'true' else False
        if dob_day and dob_month and dob_year:
            found_cat.dob = date(day=int(dob_day), month=int(dob_month), year=int(dob_year))
        if breed:
            found_cat.breed = str(breed).strip()
        if color:
            found_cat.color = str(color).strip()

        db.session.commit()
        return redirect(url_for('main.get_cats'))
    
    raise ValueError('Cat not found')

@main.route('/my-cats/<int:cat_id>/add-food/<int:food_id>/')
@login_required
def add_cat_food(cat_id, food_id):
    cat = Cat.query.get(cat_id)
    food = Food.query.get(food_id)

    if cat is None or food is None:
        return 'Invalid cat or food ID'

    existing_food = db.session.query(cat_food).filter(cat_food.c.cat_id == cat_id).first()

    if existing_food:
        delete_query = cat_food.delete().where(cat_food.c.cat_id == cat_id)
        db.session.execute(delete_query)
        db.session.commit()

    insert_query = cat_food.insert().values(cat_id=cat_id, food_id=food_id)
    db.session.execute(insert_query)
    db.session.commit()

    return 'Cat food added successfully'

core/templates/main/add.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>Add Cat</h1>
<form action="{{url_for('main.add_cat')}}" method="POST">
    <input 
    type="text"
    name="name"
    id="name"
    placeholder="Enter cat's name..." 
    required />

    <input 
    type="number"
    name="weight"
    id="weight"
    step="any"
    placeholder="Weight in Kg"  
    required />

    <label for="weight_class">
        Please select:
    </label>
    <select name="weight_class" id="weight_class">
        <option value="overwight">Overweight</option>
        <option value="normal">Normal</option>
        <option value="underweight">Underweight</option>
    </select>

    <select name="is_neutered" id="is_neutered">
        <option value="true">Has been spayed / Neutered</option>
        <option value="false">Has not been spayed / Neutered</option>
    </select>

    <input 
    type="number" 
    max="31" 
    min="1"
    name="dob_day"
    id="dob_day"
    placeholder="Date of Birth (day)">
    <input 
    type="number" 
    max="12" 
    min="1"
    name="dob_month"
    id="dob_month"
    placeholder="Date of Birth (month)">
    <input 
    type="number" 
    max="2023" 
    min="1990"
    name="dob_year"
    placeholder="Date of Birth (year)">

    <input 
    type="submit"
    value="Submit" />


</form>
{% endblock %}

core/templates/main/edit-cat.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>Edit {{found_cat.name}}</h1>
<form action="{{url_for('main.edit_cat', cat_id=found_cat.id)}}" method="POST">
    <input 
    type="text"
    name="name"
    id="name"
    placeholder="Enter cat's name..." 
    value="{{found_cat.name}}"
    required />

    <input 
    type="number"
    name="weight"
    id="weight"
    placeholder="Weight in Kg"  
    value="{{found_cat.weight}}"
    step="any"
    required />

    <label for="weight_class">
        Please select:
    </label>
    <select name="weight_class" id="weight_class">
        <option value="overwight">Overweight</option>
        <option value="normal">Normal</option>
        <option value="underweight">Underweight</option>
    </select>

    <select name="is_neutered" id="is_neutered">
        <option value="true">Has been spayed / Neutered</option>
        <option value="false">Has not been spayed / Neutered</option>
    </select>

    <input 
    type="number" 
    max="31" 
    min="1"
    name="dob_day"
    id="dob_day"
    placeholder="Date of Birth (day)"
    value="{{found_cat.dob.day}}"
    required />
    <input 
    type="number" 
    max="12" 
    min="1"
    name="dob_month"
    id="dob_month"
    placeholder="Date of Birth (month)"
    value="{{found_cat.dob.month}}"
    required />
    <input 
    type="number" 
    max="2023" 
    min="1990"
    name="dob_year"
    placeholder="Date of Birth (year)"
    value="{{found_cat.dob.year}}"
    required />

    <input 
    type="submit"
    value="Submit" />


</form>
{% endblock %}

core/templates/main/index.html
{% extends 'includes/base.html' %}
{% block content %}
 <div class="content">
    <div class="hero">

    </div>
        
        <form class="cat-form" action="/" method="GET">
            <h2>Quick Calculator</h2>
            <input type="text" name="name" placeholder="Cat's Name" required>
            <br>
            <input type="number" name="age" placeholder="Cat's Age (in years)" required>
            <br>
            <input type="number" name="weight" placeholder="Cat's Weight (in kg)" required>
            <br>
            <input type="submit" value="Calculate">
        </form>
        {% if name and age and weight %}
        <div class="quick-result">
            <h2>Result: </h2>
            <h3>Cat's Name: {{ name.title() }}</h3>
            <h3>Cat's Age: {{ age }}</h3>
            <h3>Cat's Weight: {{ weight }}kg</h3>

            <h4>{{name.title()}} requires {{calories}} calories per day</h4>
            {% if current_user.is_authenticated %}
            <h4>Please note: This is just an estimate. For a more reliable calculation
                <a href="{{url_for('main.get_cats')}}">see your cats</a> or <a href="{{url_for('main.add_cat_get')}}">
                    add a cat
                </a> 
            </h4>
            {% else %}
            <h4>Please note: This is just an estimate. For a more reliable calculation
                <a href="{{url_for('auth.register')}}">register</a> for an account or 
                <a href="{{url_for('auth.login')}}">login</a>
            </h4>
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock %}

core/templates/main/view.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>My Cats</h1>
<table>
    <thead>
        <tr>
            <th>#ID</th>
            <th>Name</th>
            <th>Weight KG</th>
            <th>Age</th>
            <th>Daily Calories</th>
            <th>Grams of Wet Food</th>
            <th>Grams of Dry Food</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in cats %}
            <tr>
                <td>{{ cat.id }}</td>
                <td>{{ cat.name }}</td>
                <td>{{ cat.weight }}</td>
                {% if cat.age > 0 %}
                    <td>{{ cat.age }} years</td>
                {% else %}
                    <td>{{cat.age_months}} months</td>
                {% endif %}
                <td>{{ cat.daily_calories }}</td>
                <td>{{ cat.grams_of_wet }}</td>
                <td>{{ cat.grams_of_dry }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

core/templates/main/view_all.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="page-title">
    <h1>{{user.first_name}}'s Cats</h1>
</div>
{% if cats %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Weight KG</th>
            <th>Age</th>
            <th>Daily Calories</th>
            <th>Grams of Wet Food</th>
            <th>Grams of Dry Food</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in cats %}
                <tr>
                    <td>
                    {{cat.name}}
                    </td>
                    <td>{{ cat.weight }}kg</td>
                    {% if cat.age > 0 %}
                        <td>{{ cat.age }} years</td>
                    {% else %}
                        <td>{{cat.age_months}} months</td>
                    {% endif %}
                    <td>{{ cat.daily_calories }}Kcal</td>
                    <td>{{ cat.grams_of_wet }}g</td>
                    <td>{{ cat.grams_of_dry }}g</td>
                    <td>
                        <span class="icon">
                            <a href="{{url_for('main.get_cat', cat_id=cat.id)}}">
                                <i class="fa-solid fa-eye"></i>
                            </a>
                        </span> 
                        <span class="icon">
                            <a href="{{url_for('main.delete_cat', cat_id=cat.id)}}">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </span>
                    </td>
                </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% if not cats %}
<p>Add your cat to get started</p>
<a href="{{url_for('main.add_cat')}}">
        Here
</a>

{% endif %}
{% endblock %}

core/templates/main/view_one.html
{% extends 'includes/base.html' %}
{% block content %}
<h1>
    {{found_cat.name}}'s Profile
</h1>
<div class="profile">
    <div class="profile-row">
        <img 
        src="https://th.bing.com/th/id/R.084856970b1ae6eeff0c6a5a37605766?rik=kQCsDiKXhlUzKg&riu=http%3a%2f%2fwww.clipartbest.com%2fcliparts%2f4cb%2f6MA%2f4cb6MARgi.png&ehk=TgGnyWu4rH8TvctUFpHarUhIQJf%2fjxsFM0UoxTokenI%3d&risl=&pid=ImgRaw&r=0" alt="{{found_cat.name}}'s image" 
        class="'profile-image"
        height="400"
        width="400"
        loading='lazy'>
        <div class="profile-text">
            {% if found_cat.age_months > 12 %}
            <p>Age: {{found_cat.age}} years</p>
            {% else %}
            <p>Age: {{found_cat.age_months}} months</p>
            {% endif %}
            <p>Weight Kg: {{found_cat.weight}}</p>
            <p>Calories / day: {{found_cat.daily_calories}}kcal</p>
            <p>Grams of dry food per day: {{ found_cat.grams_of_dry }}g</p>
            <p>Grams of wet food per day: {{ found_cat.grams_of_wet }}g</p>

        </div>        
    </div>
</div>
{% endblock %}